### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddiparser2#61]
Ok. I've fixed a lot of stuff. So it's fair to cut the first release! :heart:

TODO:

- [x] Cut a GitHub release
- [x] Publish the release to PyPI
- [x] Add the version to the docs

**Comment by DiddiLeija** [comment]
> * [x]  Publish the release to PyPI

See at https://pypi.org/project/diddiparser2/
