### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddiparser2#73]
After #71 and #72, we have a new packaging method. I want to try it on PyPI, and btw, make the new features public!

TODO:

- [x] Update the changelog
- [x] Cut the GitHub tag
- [x] Publish the release to PyPI

**Comment by DiddiLeija** [comment]
All done!

> Cut the GitHub tag

https://github.com/DiddiLeija/diddiparser2/releases/tag/1.1.0

> Publish the release to PyPI

https://pypi.org/project/diddiparser2/1.1.0/

**Comment by DiddiLeija** [comment]
**Update:** We had a little issue with uploading 1.1.0, and it's now broken. We made 1.1.0.post1, which can be safely used :)
