### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddiparser2#94]
It's finally time to cut a new DiddiParser2 release! I made several enhancements, I reworked the docs, and fixed several issues. By the way, this could be the last 1.x release, because I'm looking for a big change in the syntax!

TODO:

- [x] Update the changelog
- [x] Cut the GitHub tag
- [x] Publish the release to PyPI

**Comment by DiddiLeija** [comment]
> Update the changelog

See 9a47237.

**Comment by DiddiLeija** [comment]
> Cut the GitHub tag

https://github.com/DiddiLeija/diddiparser2/releases/tag/1.2.0

**Comment by DiddiLeija** [comment]
> Publish the release to PyPI

https://pypi.org/project/diddiparser2/1.2.0/

**Comment by DiddiLeija** [comment]
Closing out then, we have finished the release process :)
